# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
workspace ‘Dope’

target 'Dope' do
    pod 'Firebase', '>= 2.5.1'
    pod 'pop', '~> 1.0'
    pod 'Koloda', '~> 3.0.0'
    pod 'FirebaseUI/Core', '~> 0.3'
end

post_install do |installer|
    `find Pods -regex 'Pods/pop.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)pop\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end

